
server {
    include "/etc/nginx/conf.d/config/common_settings.conf";
    server_name 'demo1.com';

    include "/etc/nginx/conf.d/config/cert_self-sign.conf";
    include "/etc/nginx/conf.d/config/301_http_to_https.conf";

    location / {
        proxy_pass 'http://127.0.0.1:8099';
        include "/etc/nginx/conf.d/config/common_proxy.conf";
        include "/etc/nginx/conf.d/config/websocket.conf";
    }
}

